import React, { useState } from 'react';
import { Plus, Calendar, MapPin, User, FileText, Share2, Trash2, Clock } from 'lucide-react';
import Card from './Card';
import Button from './Button';
import Modal from './Modal';
import { useLocalStorage } from '../hooks/useLocalStorage';

function IncidentRecorder({ userId }) {
  const [incidents, setIncidents] = useLocalStorage('guardian-incidents', []);
  const [showForm, setShowForm] = useState(false);
  const [selectedIncident, setSelectedIncident] = useState(null);
  const [formData, setFormData] = useState({
    title: '',
    location: '',
    officerDetails: '',
    summary: '',
    witnesses: '',
    additional: ''
  });

  const handleSubmit = (e) => {
    e.preventDefault();
    
    const newIncident = {
      recordId: Date.now().toString(),
      userId: userId,
      timestamp: new Date().toISOString(),
      ...formData,
      sharedWith: []
    };

    setIncidents([newIncident, ...incidents]);
    setFormData({
      title: '',
      location: '',
      officerDetails: '',
      summary: '',
      witnesses: '',
      additional: ''
    });
    setShowForm(false);
  };

  const handleShare = (incident) => {
    const shareText = generateShareText(incident);
    
    if (navigator.share) {
      navigator.share({
        title: `Incident Report - ${incident.title}`,
        text: shareText,
      });
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Incident details copied to clipboard');
    }
  };

  const generateShareText = (incident) => {
    return `INCIDENT REPORT

Title: ${incident.title}
Date/Time: ${new Date(incident.timestamp).toLocaleString()}
Location: ${incident.location}
Officer Details: ${incident.officerDetails}

Summary:
${incident.summary}

${incident.witnesses ? `Witnesses: ${incident.witnesses}` : ''}
${incident.additional ? `Additional Notes: ${incident.additional}` : ''}

Generated by GuardianGuide App`;
  };

  const handleDelete = (recordId) => {
    if (confirm('Are you sure you want to delete this incident record?')) {
      setIncidents(incidents.filter(inc => inc.recordId !== recordId));
    }
  };

  return (
    <div className="space-y-6 pt-6">
      <div className="px-4">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-4xl font-bold text-text-primary mb-2">Incident Records</h1>
            <p className="text-text-secondary">Document encounters for your safety and legal protection</p>
          </div>
          <Button
            onClick={() => setShowForm(true)}
            className="flex items-center space-x-2"
          >
            <Plus className="w-4 h-4" />
            <span>New Record</span>
          </Button>
        </div>
      </div>

      {/* Quick Tips */}
      <div className="mx-4">
        <Card className="bg-blue-50 border border-blue-200">
          <h3 className="font-medium text-text-primary mb-2">Documentation Tips</h3>
          <ul className="text-sm text-text-secondary space-y-1">
            <li>• Record details as soon as possible while memory is fresh</li>
            <li>• Include specific times, locations, and officer information</li>
            <li>• Note witness information if available</li>
            <li>• Keep records private and secure</li>
          </ul>
        </Card>
      </div>

      {/* Incident List */}
      <div className="px-4 space-y-4">
        {incidents.length === 0 ? (
          <Card className="text-center py-8">
            <FileText className="w-12 h-12 text-text-secondary mx-auto mb-4" />
            <h3 className="text-lg font-medium text-text-primary mb-2">No incidents recorded</h3>
            <p className="text-text-secondary mb-4">
              Start documenting encounters to build a record for your protection.
            </p>
            <Button onClick={() => setShowForm(true)}>Create First Record</Button>
          </Card>
        ) : (
          incidents.map((incident) => (
            <Card key={incident.recordId} className="space-y-3">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <h3 className="font-semibold text-text-primary">{incident.title}</h3>
                  <div className="flex items-center space-x-4 mt-2 text-sm text-text-secondary">
                    <div className="flex items-center space-x-1">
                      <Clock className="w-4 h-4" />
                      <span>{new Date(incident.timestamp).toLocaleDateString()}</span>
                    </div>
                    {incident.location && (
                      <div className="flex items-center space-x-1">
                        <MapPin className="w-4 h-4" />
                        <span>{incident.location}</span>
                      </div>
                    )}
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  <Button
                    variant="icon"
                    size="sm"
                    onClick={() => handleShare(incident)}
                  >
                    <Share2 className="w-4 h-4" />
                  </Button>
                  <Button
                    variant="icon"
                    size="sm"
                    onClick={() => handleDelete(incident.recordId)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </div>

              <div className="text-sm text-text-primary">
                <p className="line-clamp-2">{incident.summary}</p>
              </div>

              <Button
                variant="secondary"
                size="sm"
                onClick={() => setSelectedIncident(incident)}
                className="w-full"
              >
                View Details
              </Button>
            </Card>
          ))
        )}
      </div>

      {/* New Incident Form Modal */}
      <Modal 
        isOpen={showForm} 
        onClose={() => setShowForm(false)}
        title="Document New Incident"
        size="lg"
      >
        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              Incident Title *
            </label>
            <input
              type="text"
              required
              value={formData.title}
              onChange={(e) => setFormData({...formData, title: e.target.value})}
              placeholder="Brief description of the incident"
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              Location
            </label>
            <input
              type="text"
              value={formData.location}
              onChange={(e) => setFormData({...formData, location: e.target.value})}
              placeholder="Street address or general location"
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              Officer/Personnel Details
            </label>
            <input
              type="text"
              value={formData.officerDetails}
              onChange={(e) => setFormData({...formData, officerDetails: e.target.value})}
              placeholder="Badge numbers, names, vehicle numbers, etc."
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              Incident Summary *
            </label>
            <textarea
              required
              rows={4}
              value={formData.summary}
              onChange={(e) => setFormData({...formData, summary: e.target.value})}
              placeholder="Detailed description of what happened..."
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              Witnesses
            </label>
            <input
              type="text"
              value={formData.witnesses}
              onChange={(e) => setFormData({...formData, witnesses: e.target.value})}
              placeholder="Names and contact information of witnesses"
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              Additional Notes
            </label>
            <textarea
              rows={3}
              value={formData.additional}
              onChange={(e) => setFormData({...formData, additional: e.target.value})}
              placeholder="Any other relevant information..."
              className="w-full p-3 border border-gray-300 rounded-md focus:ring-2 focus:ring-primary focus:border-transparent"
            />
          </div>

          <div className="flex justify-end space-x-3 pt-4">
            <Button
              type="button"
              variant="secondary"
              onClick={() => setShowForm(false)}
            >
              Cancel
            </Button>
            <Button type="submit">
              Save Record
            </Button>
          </div>
        </form>
      </Modal>

      {/* Incident Details Modal */}
      <Modal 
        isOpen={!!selectedIncident} 
        onClose={() => setSelectedIncident(null)}
        title="Incident Details"
        size="lg"
      >
        {selectedIncident && (
          <div className="p-6 space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <h4 className="font-medium text-text-primary mb-1">Date & Time</h4>
                <p className="text-text-secondary">{new Date(selectedIncident.timestamp).toLocaleString()}</p>
              </div>
              {selectedIncident.location && (
                <div>
                  <h4 className="font-medium text-text-primary mb-1">Location</h4>
                  <p className="text-text-secondary">{selectedIncident.location}</p>
                </div>
              )}
            </div>

            {selectedIncident.officerDetails && (
              <div>
                <h4 className="font-medium text-text-primary mb-1">Officer/Personnel Details</h4>
                <p className="text-text-secondary">{selectedIncident.officerDetails}</p>
              </div>
            )}

            <div>
              <h4 className="font-medium text-text-primary mb-1">Summary</h4>
              <p className="text-text-secondary whitespace-pre-wrap">{selectedIncident.summary}</p>
            </div>

            {selectedIncident.witnesses && (
              <div>
                <h4 className="font-medium text-text-primary mb-1">Witnesses</h4>
                <p className="text-text-secondary">{selectedIncident.witnesses}</p>
              </div>
            )}

            {selectedIncident.additional && (
              <div>
                <h4 className="font-medium text-text-primary mb-1">Additional Notes</h4>
                <p className="text-text-secondary whitespace-pre-wrap">{selectedIncident.additional}</p>
              </div>
            )}

            <div className="flex justify-end space-x-3 pt-4">
              <Button
                variant="secondary"
                onClick={() => handleShare(selectedIncident)}
                className="flex items-center space-x-2"
              >
                <Share2 className="w-4 h-4" />
                <span>Share</span>
              </Button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
}

export default IncidentRecorder;